### ISSUE TITLE
changing keymap support

### ISSUE THREAD

**Issue by Jaehaks** [ptdewey/yankbank-nvim#1]
Thanks for your efforts, 

Could you provide keymap support (move up/down) or select using number instead of <CR>?

**Comment by ptdewey** [comment]
Do you mean pressing '3' to get to entry 3 or do you mean hitting '3j' to go down 3 entries? 
I would ideally like to set up both, but if you let me know which you were looking for I can prioritize it.

**Comment by Jaehaks** [comment]
> Do you mean pressing '3' to get to entry 3 or do you mean hitting '3j' to go down 3 entries? I would ideally like to set up both, but if you let me know which you were looking for I can prioritize it.

Thanks @ptdewey .

I think that it will be convenient to paste the 3rd register contents after  I put only '3' 
but it might have delay if max_entries is over 10 because it determine whether is means between '1' and '10', 

'3j<CR>' or '3<CR>' will be good as i think. 

and can you provide keymap configuration  about moving? 
I am using switch 'j' and 'k' ....

**Comment by ptdewey** [comment]
I'll work on opening up the keymaps function to allow for adjusting the navigation keys (and the yank/paste ones as well).
I suspect the numbered navigation will be more difficult to set up but I will experiment with that as well. I suspect that pressing just one number isn't really feasible, but 'number + enter' might work well enough, so I might give that a try.

**Comment by ptdewey** [comment]
I added number navigations in 3969d03, and keymap rebinds in #3.
 
You can see the updated README for more details, but I added 2 modes, 'prefix' and 'jump'.
Prefix mode allows you to prefix a navigation key with a number and it will jump that many entries instead of lines.
Jump mode moves the cursor directly to the specified entry number, but it does have delay on pressing a key if there is a valid two-digit entry number that starts with the entered number. If that is an issue, I would just set max_entries to 9 or use prefix mode (or if you come up with a better way of jumping, feel free to open a PR).

This should address your requests, let me know if you have any other questions.

**Comment by Jaehaks** [comment]
@ptdewey 
Brilliant!
That's what I hoped !! , Thank you for your effort!
