### ISSUE TITLE
Error when running commands or opening neovim

### ISSUE THREAD

**Issue by Leonard-Pat** [ptdewey/yankbank-nvim#20]
Hello - following the recent update i get this error when performing some operations for example  if i open yank bank and press`dd` or i do `ciW` in normal mode.

<img width="1512" alt="Screenshot 2024-09-02 at 21 34 20" src="https://github.com/user-attachments/assets/4e21c391-b7e5-437a-9a5a-11476ad65ae5">

I also get this warning when opening nvim:

<img width="1336" alt="Screenshot 2024-09-02 at 21 36 46" src="https://github.com/user-attachments/assets/904ff226-e0bb-4275-9736-bd046d15e7a9">

**Comment by ptdewey** [comment]
Oh sorry about that, that is happening because I added some expanded API functionalities to the plugin (pinning and unpinning bank entries), and I had to add new fields to the sqlite table.

If you run `:YankBankClearDB`, the problem will be resolved. 

Sorry for the inconvenience, I'm not planning on making any more DB schema changes in the future though, so hopefully this will be the only time you have to do this.

**Comment by Leonard-Pat** [comment]
Wow thanks for the quick reply really appreciate it!
All solved now ❤️  and thanks for the great plugin!
